### ISSUE TITLE
Compiling with Lua 5.2 throws an error

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#566]
_From [CharlesP...@googlemail.com](https://code.google.com/u/103365645135809169866/) on August 07, 2013 13:56:54_

Hello.

Arch Linux
Corsix r2304 lua 5.2 removes luaL_typerror() which corsix uses.

lua 5.1(.5) is also installed alongside 5.2(.2), and the cmake system apparently correctly identifies it. ("  Lua 5.1 found")

However, when attempting to compile with the GNU Make step, it all fails.

[lordaro@Donald CorsixTH]$ make
[  2&#37;] Building CXX object CorsixTH/CMakeFiles/CorsixTH.dir/Src/th_lua_ui.cpp.o
In file included from /home/lordaro/coding/corsix-th/CorsixTH/Src/th_lua_internal.h:26:0,
                 from /home/lordaro/coding/corsix-th/CorsixTH/Src/th_lua_ui.cpp:23:
/home/lordaro/coding/corsix-th/CorsixTH/Src/th_lua.h: In instantiation of ‘T* luaT_testuserdata(lua_State*, int, int, bool) [with T = THMap; lua_State = lua_State]’:
/home/lordaro/coding/corsix-th/CorsixTH/Src/th_lua.h:267:51:   required from ‘T* luaT_testuserdata(lua_State*, int) [with T = THMap; lua_State = lua_State]’
/home/lordaro/coding/corsix-th/CorsixTH/Src/th_lua_ui.cpp:43:48:   required from here
/home/lordaro/coding/corsix-th/CorsixTH/Src/th_lua.h:257:56: error: ‘luaL_typeerror’ was not declared in this scope
         luaL_typerror(L, idx, luaT_classinfo<T>::name());
                                                        ^
/home/lordaro/coding/corsix-th/CorsixTH/Src/th_lua.h: In instantiation of ‘T* luaT_testuserdata(lua_State*, int, int, bool) [with T = THRenderTarget; lua_State = lua_State]’:
/home/lordaro/coding/corsix-th/CorsixTH/Src/th_lua.h:267:51:   required from ‘T* luaT_testuserdata(lua_State*, int) [with T = THRenderTarget; lua_State = lua_State]’
/home/lordaro/coding/corsix-th/CorsixTH/Src/th_lua_ui.cpp:44:69:   required from here
/home/lordaro/coding/corsix-th/CorsixTH/Src/th_lua.h:257:56: error: ‘luaL_typeerror’ was not declared in this scope
/home/lordaro/coding/corsix-th/CorsixTH/Src/th_lua.h: In instantiation of ‘T* luaT_testuserdata(lua_State*, int, int, bool) [with T = THWindowBase_t; lua_State = lua_State]’:
/home/lordaro/coding/corsix-th/CorsixTH/Src/th_lua.h:273:48:   required from ‘int luaT_stdgc(lua_State*) [with T = THWindowBase_t; int mt = -1001001; lua_State = lua_State]’
/home/lordaro/coding/corsix-th/CorsixTH/Src/th_lua_ui.cpp:167:5:   required from here
/home/lordaro/coding/corsix-th/CorsixTH/Src/th_lua.h:257:56: error: ‘luaL_typeerror’ was not declared in this scope
make[2]: *** [CorsixTH/CMakeFiles/CorsixTH.dir/Src/th_lua_ui.cpp.o] Error 1
make[1]: *** [CorsixTH/CMakeFiles/CorsixTH.dir/all] Error 2
make: *** [all] Error 2

If i remove lua (5.2) (leaving lua5.1 installed) then cmake still reports to have loaded 5.1, but fails to find any lua files at all:

[  2&#37;] Building CXX object CorsixTH/CMakeFiles/CorsixTH.dir/Src/th_lua_ui.cpp.o
In file included from /home/lordaro/coding/corsix-th/CorsixTH/Src/th_lua.h:25:0,
                 from /home/lordaro/coding/corsix-th/CorsixTH/Src/th_lua_internal.h:26,
                 from /home/lordaro/coding/corsix-th/CorsixTH/Src/th_lua_ui.cpp:23:
/home/lordaro/coding/corsix-th/CorsixTH/Src/lua.hpp:27:17: fatal error: lua.h: No such file or directory
 \#include \<lua.h>
                 ^
compilation terminated.
make[2]: *** [CorsixTH/CMakeFiles/CorsixTH.dir/Src/th_lua_ui.cpp.o] Error 1
make[1]: *** [CorsixTH/CMakeFiles/CorsixTH.dir/all] Error 2
make: *** [all] Error 2

Clearly, there is something wrong with the build environment (or even cmake itself)

Hope this helps!

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=1682_

**Comment by TheCycoONE** [comment]
CorsixTH still can't compile with Lua 5.2.  I've been working on this lately and I have it compiling now but not running.

**Comment by TheCycoONE** [comment]
Duplicate of #262 to be fixed by pr #703
