### ISSUE TITLE
Compile fails with ffmpeg 5.0

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#2109]
CorsixTH fails to compile with FFmpeg 5.0 released on January 17th 2022 due to incompatible changes to the API.

```
distcc[44717] ERROR: compile /home/stephen/corsixth/CorsixTH/Src/th_movie.cpp on 192.168.1.42:3636/8,lzo failed
distcc[44717] (dcc_build_somewhere) Warning: remote compilation of '/home/stephen/corsixth/CorsixTH/Src/th_movie.cpp' failed, retrying locally
distcc[44717] Warning: failed to distribute /home/stephen/corsixth/CorsixTH/Src/th_movie.cpp to 192.168.1.42:3636/8,lzo, running locally instead
/home/stephen/corsixth/CorsixTH/Src/th_movie.cpp: In member function ‘bool movie_player::load(const char*)’:
/home/stephen/corsixth/CorsixTH/Src/th_movie.cpp:343:52: error: invalid conversion from ‘AVCodec**’ to ‘const AVCodec**’ [-fpermissive]
  343 |                                            -1, -1, &video_decoder, 0);
      |                                                    ^~~~~~~~~~~~~~
      |                                                    |
      |                                                    AVCodec**
In file included from /home/stephen/corsixth/CorsixTH/Src/th_movie.h:47,
                 from /home/stephen/corsixth/CorsixTH/Src/th_movie.cpp:23:
/usr/include/libavformat/avformat.h:2165:41: note:   initializing argument 5 of ‘int av_find_best_stream(AVFormatContext*, AVMediaType, int, int, const AVCodec**, int)’
 2165 |                         const AVCodec **decoder_ret,
      |                         ~~~~~~~~~~~~~~~~^~~~~~~~~~~
/home/stephen/corsixth/CorsixTH/Src/th_movie.cpp:355:52: error: invalid conversion from ‘AVCodec**’ to ‘const AVCodec**’ [-fpermissive]
  355 |                                            -1, -1, &audio_decoder, 0);
      |                                                    ^~~~~~~~~~~~~~
      |                                                    |
      |                                                    AVCodec**
In file included from /home/stephen/corsixth/CorsixTH/Src/th_movie.h:47,
                 from /home/stephen/corsixth/CorsixTH/Src/th_movie.cpp:23:
/usr/include/libavformat/avformat.h:2165:41: note:   initializing argument 5 of ‘int av_find_best_stream(AVFormatContext*, AVMediaType, int, int, const AVCodec**, int)’
 2165 |                         const AVCodec **decoder_ret,
      |                         ~~~~~~~~~~~~~~~~^~~~~~~~~~~
distcc[44721] ERROR: compile (null) on localhost failed
distcc[44717] ERROR: compile /home/stephen/corsixth/CorsixTH/Src/th_movie.cpp on localhost failed
make[2]: *** [CorsixTH/CMakeFiles/CorsixTH_lib.dir/build.make:426: CorsixTH/CMakeFiles/CorsixTH_lib.dir/Src/th_movie.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:360: CorsixTH/CMakeFiles/CorsixTH_lib.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```
