### ISSUE TITLE
[Bug] Compile of 0.65 fails on compiling undesired movie

### ISSUE THREAD

**Issue by Alberth289346** [CorsixTH/CorsixTH#1999]
#### Describe the issue

Compile failure

#### Steps to Reproduce
1. Get source code
``` bash
$ git show master
commit e954dd5ceeed709cc195b7b0334504b32c403677
...
```

2. Configure
``` bash
$ mkdir build
$ cd build
$ cmake -DWITH_MOVIES:BOOL=OFF \
      -DCMAKE_BUILD_TYPE=DEBUG \
      -DCMAKE_INSTALL_PREFIX=./installed \
      -DWITH_LUAJIT:BOOL=OFF \
      -DBUILD_ANIMVIEW:BOOL=ON \
      -DCMAKE_CXX_COMPILER:FILEPATH=/usr/bin/g++ \
      -DCMAKE_C_COMPILER:FILEPATH=/usr/bin/gcc \
      ..
   ```

3. Compile the program (ie `make`)

4. Observe failure to find include file.
``` text
/home/alberth/corsix-th/corsix_alberth_fork/CorsixTH/Src/th_movie.cpp:27:10: fatal error: libavutil/channel_layout.h: No such file or directory
   27 | #include <libavutil/channel_layout.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

Code there:
https://github.com/CorsixTH/CorsixTH/blob/master/CorsixTH/Src/th_movie.cpp#L27

Corsix pussycat died :cat2:

**Comment by lewri** [comment]
At master instead of 0.65 release?
If so, are we compiling fine at 0.65?

**Comment by TheCycoONE** [comment]
Yes, this was a regression caused by https://github.com/CorsixTH/CorsixTH/commit/9955fdf3233c35f55a2059b36042910281008a1b

Fix is trivial, I'll make a PR.
